
removed_list = ['cust_id', 'phone_no', 'id_no', 'name',
	     'payment_date', 'apply_time', 'audit_time', 'payment_time',
	     'repayment_time', 'reject_reason', 'not_get_fetch_detail',
	     'repayment_type', 'pay_channel', 'created_by', 'created_time',
	     'last_modified_by', 'last_modified_time', 'upd_dt', 'st_date',
	     'min_date', 'now_city_code', 'work_area', 'reason_code',
	     'is_sms', 'is_contacts', 'refuseMessage', 'order_source',]


qualitative_variables_list =\
	['amount', 'term', 'rate', 'service_fee', 'payment_amount',
	'H1', 'source', 'channel', 'id_province', 
	'now_province', 'work_province', 'gender', 'industry',]
	
fillna_list = qualitative_variables_list +\
        ['live_city.now_city',
        'live_city.work_city',
        'live_city.id_city',
        'live_city.mobile_city',
        'live_city.ec1_city',
        'live_city.ec2_city',
        'live_city.bk_mob_city',
        'now_city.live_city',
        'now_city.work_city',
        'now_city.id_city',
        'now_city.mobile_city',
        'now_city.ec1_city',
        'now_city.ec2_city',
        'now_city.bk_mob_city',
        'work_city.live_city',
        'work_city.now_city',
        'work_city.id_city',
        'work_city.mobile_city',
        'work_city.ec1_city',
        'work_city.ec2_city',
        'work_city.bk_mob_city',
        'id_city.live_city',
        'id_city.now_city',
        'id_city.work_city',
        'id_city.mobile_city',
        'id_city.ec1_city',
        'id_city.ec2_city',
        'id_city.bk_mob_city',
        'mobile_city.live_city',
        'mobile_city.now_city',
        'mobile_city.work_city',
        'mobile_city.id_city',
        'mobile_city.ec1_city',
        'mobile_city.ec2_city',
        'mobile_city.bk_mob_city',
        'ec1_city.live_city',
        'ec1_city.now_city',
        'ec1_city.work_city',
        'ec1_city.id_city',
        'ec1_city.mobile_city',
        'ec1_city.ec2_city',
        'ec1_city.bk_mob_city',
        'ec2_city.live_city',
        'ec2_city.now_city',
        'ec2_city.work_city',
        'ec2_city.id_city',
        'ec2_city.mobile_city',
        'ec2_city.ec1_city',
        'ec2_city.bk_mob_city',
        'bk_mob_city.live_city',
        'bk_mob_city.now_city',
        'bk_mob_city.work_city',
        'bk_mob_city.id_city',
        'bk_mob_city.mobile_city',
        'bk_mob_city.ec1_city',
        'bk_mob_city.ec2_city',
        'live_area.now_area',
        'live_area.work_area',
        'live_area.id_area',
        'now_area.live_area',
        'now_area.work_area',
        'now_area.id_area',
        'work_area.live_area',
        'work_area.now_area',
        'work_area.id_area',
        'id_area.live_area',
        'id_area.now_area',
        'id_area.work_area',]
